version: '3'
services:
  web:
    command: ["./wait-for-selenium.sh", "http://selenium:4444/wd/hub", "--", "scrapy", "crawl", "companies", "-o", "./logs/users.csv"]
    environment:
      - PYTHONUNBUFFERED=0
    build:
      context: .
      dockerfile: ./docker_conf/prod/Dockerfile
    depends_on:
      - selenium
    volumes:
      - ./logs:/code/logs
  selenium:
    container_name: selenium
    image: selenium/standalone-chrome-debug
    ports:
      - "5900:5900"
    shm_size: 128M
